### ISSUE TITLE
Welcome release source code and pretrained model, Thanks

### ISSUE THREAD

**Issue by delldu** [ais-lab/feat2map#1]
Dear Friends,
    Thanks your great work, as title, welcome you release code as soon as possible.
    Many thanks.

**Comment by thuanaislab** [comment]
Hi there, 
Thanks for your interest - we are intending to release the code in the next few months with a fully updated version and some more interesting results.

**Comment by zebin-dm** [comment]
Thanks your great work,  as title, welcome you release code as soon as possible.

**Comment by matbeedotcom** [comment]
Curious how it's going :)

**Comment by thuanaislab** [comment]
Thank you for your interest in this work. We have initially uploaded the source code. However, it's not the final optimal one. If there are any issues plz contact me. Thanks
