### ISSUE TITLE
About Cambridge dataset processing

### ISSUE THREAD

**Issue by hui5552** [ais-lab/feat2map#10]
Thanks for your Great Work! After the Cambridge dataset is processed with HLOC, there are less than 2048 descriptors extracted, I would like to ask you about the corresponding HLOC setting parameters when you processed this dataset at that time, thank you！！！

**Comment by thuanaislab** [comment]
Hi, thank you for your interest in our work. I think you can follow the solution in the issue #9 https://github.com/ais-lab/feat2map/issues/9
This can help you to config the HLOC. If you still face any problem with it, feel free to mention it here. Thanks

**Comment by hui5552** [comment]
OK,I will  try again. Thank u!!!
