### ISSUE TITLE
Localizing single image to pre-trained dataset

### ISSUE THREAD

**Issue by matbeedotcom** [ais-lab/feat2map#11]
Is it possible to manually relocalize an image without further training?

**Comment by thuanaislab** [comment]
Hi, thank you for your interest. 
Do you mean relocalizing in the same environment (pre-trained scene)? 
If so, yes, you don't need further training. 
But with a different environment, you need to re-train the model.

**Comment by matbeedotcom** [comment]
Same environment, but an image not in the dataset

Would you be able to guide me on which functions to look at to achieve it?

**Comment by thuanaislab** [comment]
I assume that you already downloaded the 7scenes dataset. 
Please use the following command to run a simple demo, and then you will see how it relocalizes on a given image:

```
git pull  # Make sure you pull the latest update of demo
cd demo
python demo.py
```

Then the results should show like this: 
![image](https://github.com/ais-lab/feat2map/assets/76569397/aa38b6ce-dfb1-4cbe-8cd3-8a78a4524672)

**Comment by matbeedotcom** [comment]
Excellent! I appreciate it! I'll have time shortly to run this :)
